[package]
name = "controller"
version = "0.1.0"
authors = ["Mindaugas Sharskus <g00339629@gmit.ie>"]
edition = "2018"

[dependencies]
block_chain = { path = "../block_chain" }
miner = { path = "../miner" }
node = { path = "../node" }
