[package]
name = "toy-chain"
version = "0.1.0"
authors = [
    "tensor-programing<http://www.tensor-programming.com/>",
    "mindaugas <my>",
]
edition = "2018"

[dependencies]
time = "0.1.42"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"
sha2 = "0.8.0"