[package]
name = "block_chain"
version = "0.1.0"
authors = ["Mindaugas Sarskus <my>", "Bernard Wong <BernardWong97>"]
edition = "2018"

[dependencies]
sha2 = "0.8.0"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
