[package]
name = "using-serde"
version = "0.1.0"
authors = ["mindaugas <my>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
#toml = "0.4.10"
serde_json = "1.0"
#ron = "*"